language: php

php:
 - 5.4
 - 5.5
 - 5.6

branches:
    - master

matrix:
  include:
    - php: 5.5
      env: VARIA=true
      before_script:
        - git clone https://github.com/Elgg/Elgg.git ../Elgg && cd ../Elgg
        - git checkout 2.0
        - git clone https://github.com/$TRAVIS_REPO_SLUG.git mod/roles
        - cd mod/roles
        - git checkout -qf $TRAVIS_COMMIT
      install:
       - phpenv rehash
       - composer install
       - wget https://scrutinizer-ci.com/ocular.phar
      script:
       - phpunit --coverage-clover=coverage.clover
      after_script:
       - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

script:
 - phpunit